### ISSUE TITLE
Meeting a bug in "./seqtr/api/train.py" , 94 line, the accuracy function.

### ISSUE THREAD

**Issue by zlj63501** [sean-zhuh/SeqTR#1]
Thank author for prviding clear code. When the model trained by use "python tools/train.py configs/seqtr/segmentation/seqtr_mask_[DATASET_NAME].py --cfg-options ema=True",  the accuracy function only receives 3 return values, and this cause the training failed. According to post code, the "batch_ie" isn't a significant parameter. It seems a reminder, so I delete the code about "batch_iz" in "./seqtr/api/train.py" that it can work well. Could author gives a description about "batch_ie"? 
It would be nice if the author provided weights trained for the model. Thank you!

**Comment by sean-zhuh** [comment]
Hi,
the _batch_it_ is meant to measure the prediction conflict during multi-task learning as proposed in [MCN](https://www.bing.com/search?q=multi-task+collaborative+network&form=APMCS1&PC=APMC&adlt=strict), that is, the detection is correct but the segmentation is wrong, or the detection is right but the segmentation is correct.

**Comment by sean-zhuh** [comment]
Hi, thanks for your interest.

the _batch_ie_ is meant to measure the prediction conflict during multi-task learning as proposed in [MCN](https://www.bing.com/search?q=multi-task+collaborative+network&form=APMCS1&PC=APMC&adlt=strict), that is, the detection is correct but the segmentation is wrong, or the detection is right but the segmentation is correct. 

I delete this metric in the updated code, because multi-task learning do not bring mutual benefit to each individual task, in this case, the rec and res task, though we do provide configuration files and model support for multi-task learning.

The weights will be updated soon, because I no longer have access to the GPU server, so I need collaborators to download them for me, stay tuned. :)

**Comment by zlj63501** [comment]
Thank you for your detailed reply. Looking forward to the next update.

**Comment by zlj63501** [comment]
> Hi, thanks for your interest.
> 
> the _batch_ie_ is meant to measure the prediction conflict during multi-task learning as proposed in [MCN](https://www.bing.com/search?q=multi-task+collaborative+network&form=APMCS1&PC=APMC&adlt=strict), that is, the detection is correct but the segmentation is wrong, or the detection is right but the segmentation is correct.
> 
> I delete this metric in the updated code, because multi-task learning do not bring mutual benefit to each individual task, in this case, the rec and res task, though we do provide configuration files and model support for multi-task learning.
> 
> The weights will be updated soon, because I no longer have access to the GPU server, so I need collaborators to download them for me, stay tuned. :)

Thank you for your detailed reply. Looking forward to the next update.
